version: "3.9"

services:
  app:
    build: .
    container_name: gestion_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/colis_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 79695051
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: gestion_db
    environment:
      POSTGRES_DB: colis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 79695051
    ports:
      - "5432:5432"
    volumes:
      - gestion_data:/var/lib/postgresql/data

volumes:
  gestion_data:
