apiVersion: v1
kind: Service
metadata:
  name: gestion-service
  labels:
    app: gestion
spec:
  type: LoadBalancer
  selector:
    app: gestion
  ports:
    - port: 80
      targetPort: 8989
      protocol: TCP
      name: http
